### ISSUE TITLE
how  can I use python pytesseract 

### ISSUE THREAD

**Issue by Vivianwxf** [azmiozgen/text-detection#1]
Thanks for sharing. When I run the code, there'is some errors that I have no idea to work out, " File "D:\Program Files\Anaconda3\envs\test_py2\lib\site-packages\pytesseract\pytesseract.py", line 116, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file ./tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')"
Would you please tell  me something that I need to check out?
非常感谢，尝试了先使用短的代码来实验，还是会报同样的error，实验和error如下：
>>> from PIL import Image
>>> import pytesseract
>>> imageObject=Image.open('test.jpg')
>>> print (imageObject)
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0x5BE4CF8>
>>> print (pytesseract.image_to_string(imageObject))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Anaconda3\envs\test_py2\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "D:\Program Files\Anaconda3\envs\test_py2\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "D:\Program Files\Anaconda3\envs\test_py2\lib\site-packages\pytesseract\pytesseract.py", line 116, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file ./tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

**Comment by Vivianwxf** [comment]
Thanks a lot, I run the code in WIN10 environment， and I have already fix it。
BTW，I try to use this code to detect the car plate, but the result is not good, have you ever try to apply this way to detect the car plate?

**Comment by azmiozgen** [comment]
I have not tried on particular car plate samples. Could you share the samples you tried? Did you try text_detection_detail.py to see intermediate steps?

**Comment by Vivianwxf** [comment]
Yep, I also tried the file text_detection_detail.py to see intermediate steps, could you leave me your e-mail address or contact me with my e-mail yolo_wxfajr@163.com? I share you some samples I tried~

**Comment by azmiozgen** [comment]
My e-mail is available on my profile.

**Comment by dravibabu** [comment]
Please explain me how to execute this text detection code. i got error at this line
def getStrokes(self, (x, y, w, h)):
