### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jl-yin** [azmiozgen/text-detection#3]
yin@yin-00:~/text-detection-master/text-detection-master$ python3 text_detect.py -i ./images/scenetext01.jpg -f
  File "text_detect.py", line 130
    def getStrokes(self, (x, y, w, h)):
                         ^
SyntaxError: invalid syntax

yin@yin-00:~/text-detection-master/text-detection-master$ python3 text_detect.py -i ./images/scenetext01.jpg -o ./output
  File "text_detect.py", line 130
    def getStrokes(self, (x, y, w, h)):
                         ^
SyntaxError: invalid syntax

How should this problem be solved?

**Comment by azmiozgen** [comment]
When I execute the last committed version, I do not get such an error. It should be an indentation or parentheses error. Please give me the environment you run the code and larger code block where the error occurs.

**Comment by mit456** [comment]
@azmiozgen the errors are becuase of `python3` I believe. I have raised a pull request to support python3. 

Please have a look.

**Comment by azmiozgen** [comment]
Ok, thanks.
