### ISSUE TITLE
Why did my test result so bad?

### ISSUE THREAD

**Issue by cdsss** [azmiozgen/text-detection#6]
Thank you for sharing your code.

When I run your code for test image, I get the result here.

![result](https://user-images.githubusercontent.com/32668922/50042219-09c03380-009c-11e9-96ee-554e6383ff9c.png)

It seems to be much worse than your result. But I have no idea why that happens. Can you help me solve this problem?

**Comment by azmiozgen** [comment]
Use -t option

**Comment by cdsss** [comment]
> Use -t option

Thank you for answering. 

I have tested just now. Most of the extra text boxes have been removed, but the result is still not that good
![figure_1](https://user-images.githubusercontent.com/32668922/50042977-5e1ce080-00a7-11e9-83da-36f7453197a8.png)

![2](https://user-images.githubusercontent.com/32668922/50042986-87d60780-00a7-11e9-8b8c-a485247b1c88.png)

my script:
python text_detect.py -i images/scenetext01.jpg -t

**Comment by Srini-1981** [comment]
Dear Azmiozgen,
I am also getting the same result as mentioned by @cdsss, please let us know how did you achieve the only text detection in your test results, any response will be really appreciated.

**Comment by azmiozgen** [comment]
Some package may have caused this change in result. I updated a couple of hyper-parameters. Result should be better with -t option now. Please pull the latest version.

**Comment by cdsss** [comment]
> Some package may have caused this change in result. I updated a couple of hyper-parameters. Result should be better with -t option now. Please pull the latest version.

My problem has been solved. Thank you!

**Comment by Srini-1981** [comment]
Wonderful @azmiozgen, this looks much better now, thanks for the quick response and support. Any documentation support for this project?

**Comment by azmiozgen** [comment]
Only README.md for now
