### ISSUE TITLE
Error with no detection happen!

### ISSUE THREAD

**Issue by ShroukMansour** [azmiozgen/text-detection#8]
I've executed this command ` python text_detect.py -i images/scenetext01.jpg
` , but got this error

`Traceback (most recent call last):
  File "text_detect.py", line 344, in <module>
    res = td.detect()
  File "text_detect.py", line 286, in detect
    image, contours, hierarchies = cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
`

**Comment by azmiozgen** [comment]
This is related to OpenCV version. Please use the environment given in `requirements.txt` or `requirements.yml` .
